spring:
  application:
    name: docker-springboot-demo
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate.generate_statistics: false
      hibernate.show_sql: false
  datasource:
    url: jdbc:postgresql://postgres_db:5432/users-db?reWriteBatchedInserts=true
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8088
